### ISSUE TITLE
Extension occasionally uses regular tabs instead of existing notification tab

### ISSUE THREAD

**Issue by corvannoorloos** [sindresorhus/notifier-for-github-chrome#55] opened 2016-01-20 18:30 UTC
Since the extension uses an existing notification tab to display, not always this tab but a _regular_ tab (i.e. google.com) is being used.

Still having some difficulties narrowing this down any further, <s>but it might have something to do with already opened GitHub tabs. (i.e. github.com/sindresorhus)</s>

It might have something to do if a _regular_ tab has been used as a notifications tab in the past.

**Comment by sindresorhus** [comment] 2016-01-21 22:02
// @rojepp

**Comment by rojepp** [comment] 2016-01-22 07:34
I'll take a look in the weekend.

**Comment by rojepp** [comment] 2016-01-22 07:56
@corvannoorloos I can't reproduce. One thing I can imagine would go wrong is if, in your settings, you don't have a proper url in `Root URL`. OTOH, this should make the extension not work when clicked on as well. :/
What do you mean by *regular* tab?

**Comment by corvannoorloos** [comment] 2016-01-22 08:16
My Root URL is https://api.github.com/, which I believe is its default setting?
By a regular tab I mean any URL not GitHub related. I.e. google.com.

I'll try to uninstall/install the extension and update its key. Probably I'll be able to narrow this down shortly as it happens about once every 10 times I'm using this extension.

**Comment by rojepp** [comment] 2016-01-22 08:45
The [query](https://developer.chrome.com/extensions/tabs#method-query) method must give the wrong results for you, but I can not figure out why. Let me know if you narrow it down.

**Comment by corvannoorloos** [comment] 2016-01-22 10:12
I'm almost sure I've also seen it happen on a different occasion, but at least I am able to capture this one consistently.

![test5](https://cloud.githubusercontent.com/assets/1499293/12507902/f5a97838-c0f8-11e5-86be-9c8c7a06e554.gif)

**Comment by rojepp** [comment] 2016-01-22 10:52
I've tried having notifications both in backward and forward history, but I still get a new tab as expected.
I even tried with the specific site from your screenshot. :)

**Comment by corvannoorloos** [comment] 2016-01-22 11:01
I'll hopefully add some more info soon. I am using the Chrome dev version, so that might be the case.

**Comment by christophlingg** [comment] 2016-02-04 08:42
happens to me too

**Comment by licaon-kter** [comment] 2016-02-16 08:35
Really annonying in Opera Dev 37 too :(

**Comment by adam-thomas** [comment] 2016-03-08 15:05
I also get this behaviour.  It's very frustrating.

**Comment by Narno** [comment] 2016-03-08 17:00
The same for me.

May be a conflict with another tabs manager extension?

**Comment by adam-thomas** [comment] 2016-03-08 17:11
The only other extensions I have enabled are AdBlock and Meldium (a password manager).  I'm on Chrome on Linux if that helps.

**Comment by Narno** [comment] 2016-03-08 19:55
Maybe a side effect of a deprecated property: 0bfd865ecce5bad05ae789f9442ece46fb2e6699.

**Comment by sindresorhus** [comment] 2016-03-10 17:03
Duplicate of #60.

**Closed by sindresorhus** 2016-03-10 17:03 UTC
